Repository IMSGlobal/caliper-common-fixtures, pull requests merged in 2019-05, with the labels that each got.

#241 Add in some example use of extensions in SystemIdentifier fixtures
  v1p2/caliperEntityPerson.json
  v1p2/caliperEnvelopeEntityBatch.json
  v1p2/caliperEnvelopeMixedBatch.json
Labels: Task

#243 Navigation event with target<DigitalResource> (cc160)
  v1p2/caliperEventNavigationNavigatedToCollectionItem.json
Labels: Task

#238 Add Tool Use Collection Entity
  v1p1/caliperEntityCollection.json
Labels: Task

#234 Add survey profile fixtures
  v1p1/caliperEntityDateTimeQuestion.json
  v1p1/caliperEntityDateTimeResponse.json
  v1p1/caliperEntityMultiselectQuestion.json
  v1p1/caliperEntityMultiselectResponse.json
  v1p1/caliperEntityOpenEndedQuestion.json
  v1p1/caliperEntityOpenEndedResponse.json
  v1p1/caliperEntityQuestionnaire.json
  v1p1/caliperEntityQuestionnaireItem.json
  v1p1/caliperEntityRatingScaleResponse.json
  v1p1/caliperEntitySurvey.json
  v1p1/caliperEntitySurveyInvitation.json
  v1p1/caliperEventQuestionnaireCompleted.json
  v1p1/caliperEventQuestionnaireItemStarted.json
  v1p1/caliperEventQuestionnaireItemSubmitted.json
  v1p1/caliperEventQuestionnaireStarted.json
  v1p1/caliperEventSurveyInvitationAccepted.json
  v1p1/caliperEventSurveyInvitationSent.json
  v1p1/caliperEventSurveyOptedIn.json
Labels: Task

#247 Develop fixtures/v1p2 entity error fixtures (cc230)
  v1p2/commonErrorFixtures/CaliperEntityAssignableDigitalResource-MalformedDateToActivateInvalidDateTime.json
  v1p2/commonErrorFixtures/CaliperEntityAssignableDigitalResource-MalformedDateToShowInvalidDateTime.json
  v1p2/commonErrorFixtures/CaliperEntityAssignableDigitalResource-MalformedDateToStartOnInvalidDateTime.json
  v1p2/commonErrorFixtures/CaliperEntityAssignableDigitalResource-MalformedDateToSubmitInvalidDateTime.json
  v1p2/commonErrorFixtures/CaliperEntityAssignableDigitalResource-MalformedMaxAttemptsNotAnInt.json
  v1p2/commonErrorFixtures/CaliperEntityAssignableDigitalResource-MalformedMaxScoreNotAFloat.json
  v1p2/commonErrorFixtures/CaliperEntityAssignableDigitalResource-MalformedMaxSubmitsNotAnInt.json
  v1p2/commonErrorFixtures/caliperEntity-MalformedDescriptionNotANumber.json
  v1p2/commonErrorFixtures/caliperEntityAnnotation-MalformedAnnotatedWrongEntityType.json
  v1p2/commonErrorFixtures/caliperEntityAnnotation-MalformedAnnotatorWrongEntityType.json
  v1p2/commonErrorFixtures/caliperEntityAssessment-MalformedItemsContainsWrongEntityType.json
  v1p2/commonErrorFixtures/caliperEntityAssessment-MalformedItemsNotAList.json
  v1p2/commonErrorFixtures/caliperEntityAttempt-MalformedAssignableWrongEntityType.json
  v1p2/commonErrorFixtures/caliperEntityAttempt-MalformedAssigneeWrongEntityType.json
  v1p2/commonErrorFixtures/caliperEntityAttempt-MalformedCountNotAnInt.json
  v1p2/commonErrorFixtures/caliperEntityAttempt-MalformedDurationNotADuration.json
  v1p2/commonErrorFixtures/caliperEntityAttempt-MalformedEndedAtTimeInvalidDateTime.json
  v1p2/commonErrorFixtures/caliperEntityAttempt-MalformedIsPartOfWrongEntityType.json
  v1p2/commonErrorFixtures/caliperEntityAttempt-MalformedStartedAtTimeInvalidDateTime.json
  v1p2/commonErrorFixtures/caliperEntityAudioObject-MalformedMutedNotABoolean.json
  v1p2/commonErrorFixtures/caliperEntityAudioObject-MalformedVolumeLevelNotAString.json
  v1p2/commonErrorFixtures/caliperEntityAudioObject-MalformedVolumeMaxNotAString.json
  v1p2/commonErrorFixtures/caliperEntityAudioObject-MalformedVolumeMinNotAString.json
  v1p2/commonErrorFixtures/caliperEntityBookmarkAnnotation-MalformedBookmarkNotesNotAString.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedCreatorsListElementWrongType.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedCreatorsNotAList.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedDatePublishedNotValidDateTime.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedIsPartOfNotAString.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedKeywordsListElementWrongType.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedKeywordsNotAList.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedLearningObjectivesListElementWrongType.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedLearningObjectivesNotAList.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedMediaTypeNotAnInt.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedStorageNameNotAnInt.json
  v1p2/commonErrorFixtures/caliperEntityDigitalResource-MalformedVersionNotAnInt.json
  v1p2/commonErrorFixtures/caliperEntityHighlightAnnotation-MalformedSelectionTextNotAString.json
  v1p2/commonErrorFixtures/caliperEntityHighlightAnnotation-MalformedSelectionWrongEntityType.json
  v1p2/commonErrorFixtures/caliperEntitySharedAnnotation-MalformedWithAgentsNotAList.json
  v1p2/commonErrorFixtures/caliperEntitySharedAnnotation-MalformedWithAgentsWrongEntityType.json
  v1p2/commonErrorFixtures/caliperEntityTagAnnotation-MalformedTagsNotAList.json
  v1p2/commonErrorFixtures/caliperEntityTagAnnotation-MalformedTagsWrongListElementType.json
Labels: Bug

#242 Fixture for expected Caliper Endpoint Config payload
  v1p2/caliperEndpointConfigPayload.json
Labels: Proposal

#249 Change sentDate to dateSent to correspond with standard date property naming convention
  v1p1/caliperEntitySurveyInvitation.json
  v1p1/caliperEventSurveyInvitationAccepted.json
  v1p1/caliperEventSurveyInvitationSent.json
Labels: Bug

#254 True up v1p2 fixtures to the v1p2 core context
  v1p2/caliperEntityAggregateMeasure.json
  v1p2/caliperEntityAggregateMeasureCollection.json
  v1p2/caliperEntityComment.json
  v1p2/caliperEntityDateTimeQuestion.json
  v1p2/caliperEntityDateTimeResponse.json
  v1p2/caliperEntityLikertScale.json
  v1p2/caliperEntityLink.json
  v1p2/caliperEntityLtiLink.json
  v1p2/caliperEntityMultiselectQuestion.json
  v1p2/caliperEntityMultiselectResponse.json
  v1p2/caliperEntityMultiselectScale.json
  v1p2/caliperEntityNumericScale.json
  v1p2/caliperEntityOpenEndedQuestion.json
  v1p2/caliperEntityOpenEndedResponse.json
  v1p2/caliperEntityQuery.json
  v1p2/caliperEntityQuestion.json
  v1p2/caliperEntityQuestionnaire.json
  v1p2/caliperEntityQuestionnaireItem.json
  v1p2/caliperEntityRating.json
  v1p2/caliperEntityRatingScaleQuestion.json
  v1p2/caliperEntityRatingScaleResponse.json
  v1p2/caliperEntityScale.json
  v1p2/caliperEntitySearchResponse.json
  v1p2/caliperEntitySurvey.json
  v1p2/caliperEntitySurveyInvitation.json
  v1p2/caliperEventFeedbackCommented.json
  v1p2/caliperEventFeedbackRanked.json
  v1p2/caliperEventQuestionnaireCompleted.json
  v1p2/caliperEventQuestionnaireItemStarted.json
  v1p2/caliperEventQuestionnaireItemSubmitted.json
  v1p2/caliperEventQuestionnaireStarted.json
  v1p2/caliperEventResourceManagementCopied.json
  v1p2/caliperEventResourceManagementCreated.json
  v1p2/caliperEventResourceManagementPrinted.json
  v1p2/caliperEventSearchSearched.json
  v1p2/caliperEventSurveyInvitationAccepted.json
  v1p2/caliperEventSurveyInvitationSent.json
  v1p2/caliperEventSurveyOptedIn.json
  v1p2/caliperEventToolLaunchReturned.json
  v1p2/caliperEventToolUseUsedWithProgress.json
Labels: Task
